- name: CentOS 更新系统
  yum:
    name: '*'
    state: latest
    update_cache: 'yes'

- name: 使用 yum 安装工具
  yum:
    name: ['chrony','conntrack-tools','bash-completion','bind-utils','iotop','iperf3','ipvsadm','lsof','nmap-ncat','perf','psmisc','sshpass','socat','strace','sysstat','tar','tcpdump','telnet','tree','vim']
    state: latest
  tags:
  - yum

- name: 配置系统
  block:
  - name: 禁用SELinux
    lineinfile:
      dest: /etc/selinux/config
      regexp: "^SELINUX=.*"
      line: "SELINUX=disabled"
  - name: 关闭SELinux
    shell: "setenforce 0"
    failed_when: false
  - name: 配置内核参数
    template:
      src: custom_ops.conf.jinja
      dest: /etc/sysctl.d/custom_ops.conf
  - name: 应用内核参数
    shell: sysctl -p /etc/sysctl.d/*
  - name: 配置环境变量
    template:
      src: custom_ops.sh.jinja
      dest: /etc/profile.d/custom_ops.sh
  - name: 设定ulimit参数
    template:
      src: custom_limits.conf.jinja
      dest: /etc/security/limits.d/custom_limits.conf
  tags:
  - config_system
