offline: "yes"
docker:
  version: 20.10.9
  data_dir: /var/lib/docker
  registry_mirrors:
  - 'https://ac1rmo5p.mirror.aliyuncs.com'
  exec_opts:
  - 'native.cgroupdriver=systemd'
  insecure_registries:
  - 'registry-test.ehualu.com'
  - '172.38.50.130'
  default_address_pools: '10.38.0.0/16'
  log_opts:
    max_size: "50m"
    max_file: "5"
docker_service:
  options: '--default-ulimit nofile=1000000:1000000'