offline: "yes"
base_dir: "/mnt/d/work/eHualu/base_dir"
bin_dir: "/usr/local/bin"

containerd:
  version: "1.6.6"
  root_dir: "/var/lib/containerd"
  state_dir: "/run/containerd"
  systemd_cgroup: "true"
  sandbox_image: "registry.aliyuncs.com/dd_k8s/pause:3.6"

  registry_mirrors:
    - "https://ac1rmo5p.mirror.aliyuncs.com"
  insecure_registries:
    - "registry-test.ehualu.com"
    - "172.38.50.130"
  default_address_pools: "10.38.0.0/16"
